CREATE TABLE CUSTOMERS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50)
);

CREATE TABLE ORDERS (
	ID SERIAL PRIMARY KEY, -- Serial -> Integer
	AMOUNT DECIMAL(10, 2) NOT NULL,
	CUSTOMER_ID SERIAL NOT NULL,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

insert into customers values (1, 'John');
insert into customers (NAME) values　('Peter');
select * from customers;
insert into orders values (1, 2000000, 1);
commit;
REFRESH MATERIALIZED VIEW LARGE_ORDERS;

CREATE MATERIALIZED VIEW LARGE_ORDERS
AS SELECT C.ID, O.AMOUNT
FROM CUSTOMERS C, ORDERS O
WHERE C.ID = O.CUSTOMER_ID
AND O.AMOUNT > 100000
;

SELECT * FROM LARGE_ORDERS;