server.port: 8085

api:
    finnhub:
        token: 'ck5rdg9r01qls0umc6mgck5rdg9r01qls0umc6n0'
        domain: 'finnhub.io' # cannot have "/", otherwise, UriComponentsBuilder .build() finally
        base-url: 'api/v1'
        endpoints:
            stock:
                profile2: '/stock/profile2'
                quote: '/quote'

spring.datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'aa19888888'
spring.jpa:
    show-sql: true
    ## Hibernate Properties
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate.ddl-auto: update
    # update -> 冇table會自動create
    # validate -> check sql 有冇table

spring.sql.init:
    # schema-locations: classpath:ddl/DDL_DROPS.sql, classpath:ddl/DDL_TUSERS.sql, classpath:ddl/DDL_TPOSTS.sql
    mode: always # always